much more sensible and helpful usage/ui.

diff --git a/share/etherback b/share/etherback
--- a/share/etherback
+++ b/share/etherback
@@ -8,11 +8,15 @@ DOC_SUF='.pad.bak'
 ## CHANGE ABOVE STRING VALUES, ONLY: #############################################
 
 usage() {
-    echo "usage: $(basename $0) etherpad_text_uri backup_dir" >&2
+    echo "usage: \`$(basename $0)'  ETHERPAD_TEXT_URI BACKUP_DIR" >&2
     exit 2
 }
 
-[[ (( $# > 2 )) || (( $# == 1 )) ]] && usage
+(( $# != 2 )) && usage
+[[ -w "$BAK_DIR" ]] || {
+    printf 'Error: backup directory,"%s", not writeable.\n' "$BAK_DIR" >&2
+    exit 2
+}
 
 backup() {
     curl -s "$DOC_URI" > "$BAK_DIR/${DOC_PRE}$(date --rfc-3339=date)_$(date +%s)${DOC_SUF}"
