plans in motion for notifychanges

diff --git a/share/notifychanges b/share/notifychanges
--- a/share/notifychanges
+++ b/share/notifychanges
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+exit 99
 
 WATCH="${1:-$HOME/pub/drop}"
 INOTIFY='http://github.com/rvoicilas/inotify-tools'
@@ -49,15 +50,20 @@ done
 if [[ -r $WATCH ]];then
     recurse='-r'
 else
-    echo 'error: cannot find ' >&2
+    echo "error: cannot find '$WATCH'" >&2
     exit 3
 fi
 
 #@TODO: repalce this loop with proper `inotifywait -m`
 #@TODO: read inotifywait(1) EVENTS section to figure out what you do and don't
 #       want to libnotify for
+
+#@TODO: create a file descriptor to stream output to. continual read from that
+#descriptor in your loop below
+inotifywait --monitor $recurse --format '%e' $WATCH &
+N_PID=$!
 while true;do
-    if [[ $(inotifywait $recurse --format '%e' $WATCH) ]];then
+    if [[ $(inotifywait --monitor $recurse --format '%e' $WATCH) ]];then
 #       declare -a suspects
         declare suspects
         tmpf=$(mktemp)
