rewrite very old script to: a) be shell i kind of trust more; b) fallback on `zenity` (eg: when using gnome3)

diff --git a/share/notifychanges b/share/notifychanges
--- a/share/notifychanges
+++ b/share/notifychanges
@@ -1,88 +1,81 @@
 #!/usr/bin/env bash
+declare -r depends=(inotifywait)
 
-if (( $# > 1 )) && [[ $1 = '-s' ]];then
-    USE_STDOUT=1
+opt_useStdout=0
+if [ "$#" -gt 0 ] && [ "$1" = '-s' ];then
+    opt_useStdout=1
     shift;
 fi
 
-WATCH="${1:-$HOME/pub/drop}"
-INOTIFY='http://github.com/rvoicilas/inotify-tools'
-LIBNOTIFY='http://www.galago-project.org'
-depends=(inotifywait notify-send)
-HEADER="Someone Just Touched: $WATCH"
+declare -r scriptName="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"
+declare -r opt_dirToWatch="${1:-.}"
 
 usage() {
-    echo -e "
-    Continuously watch a file (or directory) and notify you of changes using
-    using libnotify. You most likely will want to background this process and
-    run it as a daemon.
+    printf '
+    Notifies you of changes to file under a given directory, using libnotify.
 
-    usage: $(basename $0) [-s] [file_name ...]
-        where file_name is the name of a dile or directory you'd like to be
-        notified of changes to.
+    Usage: %s [-s] [DIRECTORY_TO_WATCH]
+        - DIRECTORY_TO_WATCH is the name of a directory whose changes
+        notifications should be created for. Defaults to the current directory.
 
         -s  Indicates that messages should be printed to stdout instead of the
-            default notify-send(1).
+        default notify-send(1) or zenity(1).
 
-        eg.: \`$(basename $0) ~/pub/drop\`
+    Example usage:
+       `%s ~/pub/drop`
 
-    NOTE:
-        Multiple filename arguments has not been tested with this script.
-        See: notify-send(1) $INOTIFY
-        See: inotifywait(1) $LIBNOTIFY
-    " >&2
+       `%s -s ~/pub/drop | while read notification; do /bin/feed-hamster; done`
+
+    See: notify-send(1) http://github.com/rvoicilas/inotify-tools
+    See: inotifywait(1) http://www.galago-project.org
+    \r' "$scriptName" "$scriptName" >&2
     exit 2
 }
 
-dependency() {
-    echo -e "'$1' not found.\nPlease install all dependencies to this script." >&2
-    usage
-    exit 3
-}
+#
+# dependencies/usage checking
+#
 
-#for friends who don't like reading source code:
-if [[ $1 = '--help' || $1 = '-h' ]];then
-    usage
-fi
-
-#for the same friends
-for util in ${depends[@]}; do
-    if (( USE_STDOUT )) && [[ $util = 'notify-send' ]]; then
-        continue;
-    fi
-    type -p "$util" >&/dev/null || dependency "$util"
-done
-
+haveBin() { type "$1" >/dev/null 2>&1; }
+missingBin() { printf 'Error: %s missing, but required\n' "$1" >&2; usage; }
+[ "$1" = '--help' ] || [ "$1" = '-h' ] && usage
+for util in "${depends[@]}"; do haveBin "$util" || missingBin "$util"; done
+{ [ "$opt_useStdout" -eq 0 ] && ! haveBin zenity && ! haveBin notify-send; } &&
+    missingBin 'zenity or notify-send'
 
 # if inotifywait is passed a non-existent directory,
 # it goes into a monsterous infinate loop instead of failing.
-if [[ -r $WATCH ]];then
-    recurse='--recursive'
-else
-    echo "Error: cannot find '$WATCH' in filesystem" >&2
+{ [ -r "$opt_dirToWatch" ] && [ -d "$opt_dirToWatch" ]; } || {
+    printf 'Error: cannot find "%s" in filesystem\n' "$opt_dirToWatch" >&2
     exit 3
-fi
-
-iwait() {
-    inotifywait \
-        --recursive \
-        --monitor \
-        --timefmt='%H:%M:%S' \
-        --format='%T (%e) | "%f"' \
-        --event delete \
-        --event move \
-        --event create \
-        --event modify \
-        "$WATCH"
 }
 
-# the actual magic:
-if (( USE_STDOUT ));then
-    iwait
-else
-    while read -r message; do
-        notify-send "$message"
-    done < <(iwait)
-fi
+#
+# actual functional logic
+#
 
-# vim: et:sw=4:ts=4
+notify() {
+    if haveBin notify-send; then
+        notify-send "$1"
+    elif haveBin zenity; then
+        zenity --notification --text="$1"
+    fi
+}
+
+inotifywait \
+    --recursive \
+    --monitor \
+    --timefmt='%H:%M:%S' \
+    --format='%T (%e) | "%f"' \
+    --event delete \
+    --event move \
+    --event create \
+    --event modify \
+    --quiet \
+    "$opt_dirToWatch" | {
+    if [ "$opt_useStdout" -eq 0 ];then
+        while read -r message; do notify "$message"; done
+    else
+        cat /dev/stdin
+    fi
+}
