created `init` to ensure punchcard function exists. refactored method for passing options, specifically: single passing of project name.

diff --git a/share/punch b/share/punch
--- a/share/punch
+++ b/share/punch
@@ -98,14 +98,17 @@ usage() {
 
 declare -A OPTS
 OPTS=(
-    [c:]="name  Punch in/out on for a client/project of '__'."
+    [c]="Punch in/out for a 'client'/'project' being referenced. See -p."
     [d:]="timestamp  Delete a time-card entry at '__'. Note, this deletes in and out entries."
     [h]="Help message."
-    [l]="List all existing time-card entries."
-    [q:]="name  Query time-card for listing of all entries under project '__'."
-    [r:]="name  Delete all time-card entries made under project '__'."
-    [s]="Output all timestamps in epoch format, useful for immediate interpretation."
-    [t:]="name  Sum of time-card entries to-date under project '__'."
+    [l]="List all time-card entries, for every project."
+    [L]="List all time-card made under a project. See -p."
+    [n:]="note  Note about this particular card-punch '__'. See -c."
+    [p:]="name  Specify the project being referenced, as project '__'."
+    [q]="Quiet mode, print minimal output and even fail quietly."
+    [r]="name  Delete all time-card entries made under a project. See -p."
+    [s]="Output timestamps as epoch, intended as shell input. See eval(1p)."
+    [t]="Sum of total time-card entries under project. See -p."
 )
 
 
@@ -170,30 +173,32 @@ reset() {
 
 # sanity-checks: ##############################################################
 
-if [[ $(file -bL $PUNCH_CARD 2>/dev/null | grep -i 'sqlite') ]];then
-    #punch card looks like an sqlite file.
-    if [[ ! -w $PUNCH_CARD ]];then
-        error "No write-access to punch-card."
-        die $E_DATAF
-    fi
-else
-    #punch card does not look like an sqlite file.
-    if [[ -f $PUNCH_CARD ]];then
-        #punch card at least likes like _some_ kind of file.
-        if (( 10#$(stat -L --printf='%s' $PUNCH_CARD 2>/dev/null) ));then
-            #punch card has something else in it.
-            error "punch-card does not seem to be an sqlite3 database:\n\t$(file -L $PUNCH_CARD)"
+init() {
+    if [[ $(file -bL $PUNCH_CARD 2>/dev/null | grep -i 'sqlite') ]];then
+        #punch card looks like an sqlite file.
+        if [[ ! -w $PUNCH_CARD ]];then
+            error "No write-access to punch-card."
             die $E_DATAF
-        else
-            #punch card is an empty file. create tables?
-            [[ -w $PUNCH_CARD && -r $PUNCH_CARD ]] && create_db || die $?
         fi
     else
-        #punch card does not exist. create it?
-        error "Could not find punch-card\n\twas expecting: '$PUNCH_CARD'."
-        [[ -w $(dirname $PUNCH_CARD) ]] && create_db || die $?
+        #punch card does not look like an sqlite file.
+        if [[ -f $PUNCH_CARD ]];then
+            #punch card at least likes like _some_ kind of file.
+            if (( 10#$(stat -L --printf='%s' $PUNCH_CARD 2>/dev/null) ));then
+                #punch card has something else in it.
+                error "punch-card does not seem to be an sqlite3 database:\n\t$(file -L $PUNCH_CARD)"
+                die $E_DATAF
+            else
+                #punch card is an empty file. create tables?
+                [[ -w $PUNCH_CARD && -r $PUNCH_CARD ]] && create_db || die $?
+            fi
+        else
+            #punch card does not exist. create it?
+            error "Could not find punch-card\n\twas expecting: '$PUNCH_CARD'."
+            [[ -w $(dirname $PUNCH_CARD) ]] && create_db || die $?
+        fi
     fi
-fi
+}
 
 # punchcard tools: ############################################################
 
@@ -274,6 +279,10 @@ spent() {
 }
 
 # main: #######################################################################
+#@TODO: fix all the below calls and above functions to match the new getopts
+# string
+#@TODO: make sure multiple flags can be passed and they'll all be  processed
+# correctly. This means not exiting immediately after an operation.
 #@TODO: create a TRAP that will rollback transactions, `reset`
 if (( $# ));then
     #parse arguments
@@ -281,11 +290,13 @@ if (( $# ));then
         case $option in
             c)
                 declare -r OPT_PROJECT=$OPTARG
+                init
                 punch
                 die $?
                 ;;
             d)
                 declare -r OPT_DELETE=$OPTARG
+                init
                 delete
                 die $?
                 ;;
@@ -293,20 +304,24 @@ if (( $# ));then
                 help
                 ;;
             l)
+                init
                 list
                 die $?
                 ;;
             p)
+                init
                 projects
                 die $?
                 ;;
             q)
                 declare -r OPT_PROJECT=$OPTARG
+                init
                 query
                 die $?
                 ;;
             r)
                 declare -r OPT_PROJECT=$OPTARG
+                init
                 remove
                 die $?
                 ;;
@@ -315,6 +330,7 @@ if (( $# ));then
                 ;;
             t)
                 declare -r OPT_PROJECT=$OPTARG
+                init
                 spent
                 die $?
                 ;;
