make sure sqlite3 exists before even doing _anything_

diff --git a/share/punch b/share/punch
--- a/share/punch
+++ b/share/punch
@@ -1,6 +1,11 @@
 #!/bin/bash
  #@TODO: use this! #!/usr/bin/env bash
 
+if [[ ! $(type sqlite3 &>/dev/null) ]];then
+    echo "${0^} relies on sqlite3, which was not found on this system." >&2
+    exit 1
+fi
+
  #@TODO: change all user-facing wording to use "punch-card" as verbage instead
  # of "time-card"
 
